### ISSUE TITLE
run.bat

### ISSUE THREAD

**Issue by 1reqegqgbqegd313** [Riremito/JMSv186#3]
手順通りに進めてみたのですが、run.batを起動するという手順でserver.Startが見つからなかったかロード出来ませんでしたというエラーが出てしまい起動できません。

**Comment by 1reqegqgbqegd313** [comment]
[2023/02/26 15:44:58] JMS Emulate Server for v186.1
[2023/02/26 15:44:58] Starting main...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at server.Start.main(Start.java:190)
Caused by: java.lang.NullPointerException
        at provider.WzXML.XMLWZFile.fillMapleDataEntitys(XMLWZFile.java:45)
        at provider.WzXML.XMLWZFile.<init>(XMLWZFile.java:41)
        at provider.MapleDataProviderFactory.getWZ(MapleDataProviderFactory.java:34)
        at provider.MapleDataProviderFactory.getDataProvider(MapleDataProviderFactory.java:40)
        at handling.login.LoginInformationProvider.<init>(LoginInformationProvider.java:46)
        at handling.login.LoginInformationProvider.<clinit>(LoginInformationProvider.java:36)
        ... 1 more
続行するには何かキーを押してください . . .

**Comment by 1reqegqgbqegd313** [comment]
set WZ_XML_PATH=C:\Users\elfenlied\Desktop\wz\v%MS_VERSION%\

**Comment by 1reqegqgbqegd313** [comment]
すいません、自己解決しました

**Comment by Riremito** [comment]
今度修正しておきます
